// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module debug_fifo_Loop_VITIS_LOOP_20_1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        in_data,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        size,
        size_c_din,
        size_c_full_n,
        size_c_write,
        size_c_num_data_valid,
        size_c_fifo_cap,
        fifo_stream_din,
        fifo_stream_full_n,
        fifo_stream_write,
        fifo_stream_num_data_valid,
        fifo_stream_fifo_cap
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [30:0] p_read;
input  [63:0] in_data;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [31:0] m_axi_gmem0_0_WDATA;
output  [3:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [31:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [8:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [31:0] size;
output  [31:0] size_c_din;
input   size_c_full_n;
output   size_c_write;
input  [2:0] size_c_num_data_valid;
input  [2:0] size_c_fifo_cap;
output  [31:0] fifo_stream_din;
input   fifo_stream_full_n;
output   fifo_stream_write;
input  [10:0] fifo_stream_num_data_valid;
input  [10:0] fifo_stream_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem0_0_ARVALID;
reg[63:0] m_axi_gmem0_0_ARADDR;
reg[0:0] m_axi_gmem0_0_ARID;
reg[31:0] m_axi_gmem0_0_ARLEN;
reg[2:0] m_axi_gmem0_0_ARSIZE;
reg[1:0] m_axi_gmem0_0_ARBURST;
reg[1:0] m_axi_gmem0_0_ARLOCK;
reg[3:0] m_axi_gmem0_0_ARCACHE;
reg[2:0] m_axi_gmem0_0_ARPROT;
reg[3:0] m_axi_gmem0_0_ARQOS;
reg[3:0] m_axi_gmem0_0_ARREGION;
reg[0:0] m_axi_gmem0_0_ARUSER;
reg m_axi_gmem0_0_RREADY;
reg size_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    size_c_blk_n;
reg   [31:0] size_read_reg_123;
reg    ap_block_state1;
reg   [30:0] p_read_2_reg_128;
wire   [63:0] zext_ln20_fu_98_p1;
wire  signed [61:0] trunc_ln_fu_102_p4;
reg   [61:0] trunc_ln_reg_138;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_done;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_idle;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_ready;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWID;
wire   [31:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWUSER;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WVALID;
wire   [31:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WDATA;
wire   [3:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WSTRB;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WID;
wire   [0:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WUSER;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARID;
wire   [31:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARUSER;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_RREADY;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_BREADY;
wire   [31:0] grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_fifo_stream_din;
wire    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_fifo_stream_write;
reg    grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire  signed [63:0] sext_ln20_fu_112_p1;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start_reg = 1'b0;
end

debug_fifo_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1 grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start),
    .ap_done(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_done),
    .ap_idle(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_idle),
    .ap_ready(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(m_axi_gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(m_axi_gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(m_axi_gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(m_axi_gmem0_0_RLAST),
    .m_axi_gmem0_0_RID(m_axi_gmem0_0_RID),
    .m_axi_gmem0_0_RFIFONUM(m_axi_gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(m_axi_gmem0_0_RUSER),
    .m_axi_gmem0_0_RRESP(m_axi_gmem0_0_RRESP),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .fifo_stream_din(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_fifo_stream_din),
    .fifo_stream_full_n(fifo_stream_full_n),
    .fifo_stream_write(grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_fifo_stream_write),
    .fifo_stream_num_data_valid(11'd0),
    .fifo_stream_fifo_cap(11'd0),
    .size(size_read_reg_123),
    .sext_ln20(trunc_ln_reg_138)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state11) & (grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start_reg <= 1'b1;
        end else if ((grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_ready == 1'b1)) begin
            grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_read_2_reg_128 <= p_read;
        size_read_reg_123 <= size;
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln_reg_138 <= {{in_data[63:2]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem0_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((m_axi_gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_0_ARADDR = sext_ln20_fu_112_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARADDR = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARADDR;
    end else begin
        m_axi_gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARBURST = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARBURST;
    end else begin
        m_axi_gmem0_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARCACHE = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARCACHE;
    end else begin
        m_axi_gmem0_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARID = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARID;
    end else begin
        m_axi_gmem0_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_0_ARLEN = zext_ln20_fu_98_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARLEN = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARLEN;
    end else begin
        m_axi_gmem0_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARLOCK = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARLOCK;
    end else begin
        m_axi_gmem0_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARPROT = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARPROT;
    end else begin
        m_axi_gmem0_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARQOS = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARQOS;
    end else begin
        m_axi_gmem0_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARREGION = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARREGION;
    end else begin
        m_axi_gmem0_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARSIZE = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARSIZE;
    end else begin
        m_axi_gmem0_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARUSER = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARUSER;
    end else begin
        m_axi_gmem0_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_ARVALID = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_ARVALID;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem0_0_RREADY = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_m_axi_gmem0_0_RREADY;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        size_c_blk_n = size_c_full_n;
    end else begin
        size_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        size_c_write = 1'b1;
    end else begin
        size_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((size_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign fifo_stream_din = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_fifo_stream_din;

assign fifo_stream_write = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_fifo_stream_write;

assign grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start = grp_Loop_VITIS_LOOP_20_1_proc_Pipeline_VITIS_LOOP_20_1_fu_88_ap_start_reg;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 32'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 4'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign sext_ln20_fu_112_p1 = trunc_ln_fu_102_p4;

assign size_c_din = size;

assign trunc_ln_fu_102_p4 = {{in_data[63:2]}};

assign zext_ln20_fu_98_p1 = p_read_2_reg_128;

endmodule //debug_fifo_Loop_VITIS_LOOP_20_1_proc
