// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="debug_fifo_debug_fifo,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=15.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.550000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=2536,HLS_SYN_LUT=2928,HLS_VERSION=2025_1}" *)

module debug_fifo (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] in_data;
wire   [63:0] out_data;
wire   [31:0] size;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
wire    gmem0_0_ARREADY;
wire    gmem0_0_RVALID;
wire   [31:0] gmem0_0_RDATA;
wire    gmem0_0_RLAST;
wire   [0:0] gmem0_0_RID;
wire   [8:0] gmem0_0_RFIFONUM;
wire   [0:0] gmem0_0_RUSER;
wire   [1:0] gmem0_0_RRESP;
wire    gmem0_0_BVALID;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
wire    gmem1_0_ARREADY;
wire    gmem1_0_RVALID;
wire   [31:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
wire   [1:0] gmem1_0_BRESP;
wire   [0:0] gmem1_0_BID;
wire   [0:0] gmem1_0_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire   [63:0] entry_proc_U0_out_data_c_din;
wire    entry_proc_U0_out_data_c_write;
wire    Block_entry_proc_U0_ap_start;
wire    Block_entry_proc_U0_ap_done;
wire    Block_entry_proc_U0_ap_continue;
wire    Block_entry_proc_U0_ap_idle;
wire    Block_entry_proc_U0_ap_ready;
wire   [30:0] Block_entry_proc_U0_ap_return_0;
wire   [30:0] Block_entry_proc_U0_ap_return_1;
wire    ap_channel_done_p_loc6_channel;
wire    p_loc6_channel_full_n;
reg    ap_sync_reg_channel_write_p_loc6_channel;
wire    ap_sync_channel_write_p_loc6_channel;
wire    ap_channel_done_p_loc_channel;
wire    p_loc_channel_full_n;
reg    ap_sync_reg_channel_write_p_loc_channel;
wire    ap_sync_channel_write_p_loc_channel;
wire    Loop_VITIS_LOOP_20_1_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_20_1_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_20_1_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_20_1_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_20_1_proc_U0_ap_ready;
wire    Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWVALID;
wire   [63:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWID;
wire   [31:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWUSER;
wire    Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WVALID;
wire   [31:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WDATA;
wire   [3:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WSTRB;
wire    Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WLAST;
wire   [0:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WID;
wire   [0:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WUSER;
wire    Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARVALID;
wire   [63:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARID;
wire   [31:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARUSER;
wire    Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_RREADY;
wire    Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_BREADY;
wire   [31:0] Loop_VITIS_LOOP_20_1_proc_U0_size_c_din;
wire    Loop_VITIS_LOOP_20_1_proc_U0_size_c_write;
wire   [31:0] Loop_VITIS_LOOP_20_1_proc_U0_fifo_stream_din;
wire    Loop_VITIS_LOOP_20_1_proc_U0_fifo_stream_write;
wire    Loop_VITIS_LOOP_25_2_proc_U0_ap_start;
wire    Loop_VITIS_LOOP_25_2_proc_U0_ap_done;
wire    Loop_VITIS_LOOP_25_2_proc_U0_ap_continue;
wire    Loop_VITIS_LOOP_25_2_proc_U0_ap_idle;
wire    Loop_VITIS_LOOP_25_2_proc_U0_ap_ready;
wire    Loop_VITIS_LOOP_25_2_proc_U0_out_data_read;
wire    Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWVALID;
wire   [63:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWADDR;
wire   [0:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWID;
wire   [31:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWLEN;
wire   [2:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWSIZE;
wire   [1:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWBURST;
wire   [1:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWLOCK;
wire   [3:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWCACHE;
wire   [2:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWPROT;
wire   [3:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWQOS;
wire   [3:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWREGION;
wire   [0:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWUSER;
wire    Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WVALID;
wire   [31:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WDATA;
wire   [3:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WSTRB;
wire    Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WLAST;
wire   [0:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WID;
wire   [0:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WUSER;
wire    Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARVALID;
wire   [63:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARADDR;
wire   [0:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARID;
wire   [31:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARLEN;
wire   [2:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARSIZE;
wire   [1:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARBURST;
wire   [1:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARLOCK;
wire   [3:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARCACHE;
wire   [2:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARPROT;
wire   [3:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARQOS;
wire   [3:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARREGION;
wire   [0:0] Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARUSER;
wire    Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_RREADY;
wire    Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_BREADY;
wire    Loop_VITIS_LOOP_25_2_proc_U0_size_read;
wire    Loop_VITIS_LOOP_25_2_proc_U0_fifo_stream_read;
wire    out_data_c_full_n;
wire   [63:0] out_data_c_dout;
wire    out_data_c_empty_n;
wire   [2:0] out_data_c_num_data_valid;
wire   [2:0] out_data_c_fifo_cap;
wire   [30:0] p_loc_channel_dout;
wire    p_loc_channel_empty_n;
wire   [2:0] p_loc_channel_num_data_valid;
wire   [2:0] p_loc_channel_fifo_cap;
wire   [30:0] p_loc6_channel_dout;
wire    p_loc6_channel_empty_n;
wire   [2:0] p_loc6_channel_num_data_valid;
wire   [2:0] p_loc6_channel_fifo_cap;
wire    size_c_full_n;
wire   [31:0] size_c_dout;
wire    size_c_empty_n;
wire   [2:0] size_c_num_data_valid;
wire   [2:0] size_c_fifo_cap;
wire    fifo_stream_full_n;
wire   [31:0] fifo_stream_dout;
wire    fifo_stream_empty_n;
wire   [10:0] fifo_stream_num_data_valid;
wire   [10:0] fifo_stream_fifo_cap;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_Block_entry_proc_U0_ap_ready;
wire    ap_sync_Block_entry_proc_U0_ap_ready;
reg    ap_sync_reg_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready;
wire    ap_sync_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_p_loc6_channel = 1'b0;
#0 ap_sync_reg_channel_write_p_loc_channel = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Block_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready = 1'b0;
end

debug_fifo_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_data(in_data),
    .out_data(out_data),
    .size(size),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

debug_fifo_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARADDR),
    .I_CH0_ARLEN(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

debug_fifo_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWVALID),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWADDR),
    .I_CH0_AWLEN(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWLEN),
    .I_CH0_WVALID(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WVALID),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WDATA),
    .I_CH0_WSTRB(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WSTRB),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_BREADY)
);

debug_fifo_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .out_data(out_data),
    .out_data_c_din(entry_proc_U0_out_data_c_din),
    .out_data_c_full_n(out_data_c_full_n),
    .out_data_c_write(entry_proc_U0_out_data_c_write),
    .out_data_c_num_data_valid(out_data_c_num_data_valid),
    .out_data_c_fifo_cap(out_data_c_fifo_cap)
);

debug_fifo_Block_entry_proc Block_entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry_proc_U0_ap_start),
    .ap_done(Block_entry_proc_U0_ap_done),
    .ap_continue(Block_entry_proc_U0_ap_continue),
    .ap_idle(Block_entry_proc_U0_ap_idle),
    .ap_ready(Block_entry_proc_U0_ap_ready),
    .size(size),
    .ap_return_0(Block_entry_proc_U0_ap_return_0),
    .ap_return_1(Block_entry_proc_U0_ap_return_1)
);

debug_fifo_Loop_VITIS_LOOP_20_1_proc Loop_VITIS_LOOP_20_1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_20_1_proc_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_20_1_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_20_1_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_20_1_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_20_1_proc_U0_ap_ready),
    .p_read(p_loc_channel_dout),
    .in_data(in_data),
    .m_axi_gmem0_0_AWVALID(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(gmem0_0_RLAST),
    .m_axi_gmem0_0_RID(gmem0_0_RID),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(gmem0_0_RUSER),
    .m_axi_gmem0_0_RRESP(gmem0_0_RRESP),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(Loop_VITIS_LOOP_20_1_proc_U0_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .size(size),
    .size_c_din(Loop_VITIS_LOOP_20_1_proc_U0_size_c_din),
    .size_c_full_n(size_c_full_n),
    .size_c_write(Loop_VITIS_LOOP_20_1_proc_U0_size_c_write),
    .size_c_num_data_valid(size_c_num_data_valid),
    .size_c_fifo_cap(size_c_fifo_cap),
    .fifo_stream_din(Loop_VITIS_LOOP_20_1_proc_U0_fifo_stream_din),
    .fifo_stream_full_n(fifo_stream_full_n),
    .fifo_stream_write(Loop_VITIS_LOOP_20_1_proc_U0_fifo_stream_write),
    .fifo_stream_num_data_valid(fifo_stream_num_data_valid),
    .fifo_stream_fifo_cap(fifo_stream_fifo_cap)
);

debug_fifo_Loop_VITIS_LOOP_25_2_proc Loop_VITIS_LOOP_25_2_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_VITIS_LOOP_25_2_proc_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_25_2_proc_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_25_2_proc_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_25_2_proc_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_25_2_proc_U0_ap_ready),
    .p_read(p_loc6_channel_dout),
    .out_data_dout(out_data_c_dout),
    .out_data_empty_n(out_data_c_empty_n),
    .out_data_read(Loop_VITIS_LOOP_25_2_proc_U0_out_data_read),
    .out_data_num_data_valid(out_data_c_num_data_valid),
    .out_data_fifo_cap(out_data_c_fifo_cap),
    .m_axi_gmem1_0_AWVALID(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(gmem1_0_AWREADY),
    .m_axi_gmem1_0_AWADDR(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(gmem1_0_WREADY),
    .m_axi_gmem1_0_WDATA(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(1'b0),
    .m_axi_gmem1_0_ARADDR(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(1'b0),
    .m_axi_gmem1_0_RREADY(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(32'd0),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(9'd0),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(gmem1_0_BVALID),
    .m_axi_gmem1_0_BREADY(Loop_VITIS_LOOP_25_2_proc_U0_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(gmem1_0_BRESP),
    .m_axi_gmem1_0_BID(gmem1_0_BID),
    .m_axi_gmem1_0_BUSER(gmem1_0_BUSER),
    .size_dout(size_c_dout),
    .size_empty_n(size_c_empty_n),
    .size_read(Loop_VITIS_LOOP_25_2_proc_U0_size_read),
    .size_num_data_valid(size_c_num_data_valid),
    .size_fifo_cap(size_c_fifo_cap),
    .fifo_stream_dout(fifo_stream_dout),
    .fifo_stream_empty_n(fifo_stream_empty_n),
    .fifo_stream_read(Loop_VITIS_LOOP_25_2_proc_U0_fifo_stream_read),
    .fifo_stream_num_data_valid(fifo_stream_num_data_valid),
    .fifo_stream_fifo_cap(fifo_stream_fifo_cap)
);

debug_fifo_fifo_w64_d4_S out_data_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_out_data_c_din),
    .if_full_n(out_data_c_full_n),
    .if_write(entry_proc_U0_out_data_c_write),
    .if_dout(out_data_c_dout),
    .if_empty_n(out_data_c_empty_n),
    .if_read(Loop_VITIS_LOOP_25_2_proc_U0_out_data_read),
    .if_num_data_valid(out_data_c_num_data_valid),
    .if_fifo_cap(out_data_c_fifo_cap)
);

debug_fifo_fifo_w31_d2_S p_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_0),
    .if_full_n(p_loc_channel_full_n),
    .if_write(ap_channel_done_p_loc_channel),
    .if_dout(p_loc_channel_dout),
    .if_empty_n(p_loc_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_20_1_proc_U0_ap_ready),
    .if_num_data_valid(p_loc_channel_num_data_valid),
    .if_fifo_cap(p_loc_channel_fifo_cap)
);

debug_fifo_fifo_w31_d3_S p_loc6_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_1),
    .if_full_n(p_loc6_channel_full_n),
    .if_write(ap_channel_done_p_loc6_channel),
    .if_dout(p_loc6_channel_dout),
    .if_empty_n(p_loc6_channel_empty_n),
    .if_read(Loop_VITIS_LOOP_25_2_proc_U0_ap_ready),
    .if_num_data_valid(p_loc6_channel_num_data_valid),
    .if_fifo_cap(p_loc6_channel_fifo_cap)
);

debug_fifo_fifo_w32_d2_S size_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_20_1_proc_U0_size_c_din),
    .if_full_n(size_c_full_n),
    .if_write(Loop_VITIS_LOOP_20_1_proc_U0_size_c_write),
    .if_dout(size_c_dout),
    .if_empty_n(size_c_empty_n),
    .if_read(Loop_VITIS_LOOP_25_2_proc_U0_size_read),
    .if_num_data_valid(size_c_num_data_valid),
    .if_fifo_cap(size_c_fifo_cap)
);

debug_fifo_fifo_w32_d1024_A fifo_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_20_1_proc_U0_fifo_stream_din),
    .if_full_n(fifo_stream_full_n),
    .if_write(Loop_VITIS_LOOP_20_1_proc_U0_fifo_stream_write),
    .if_dout(fifo_stream_dout),
    .if_empty_n(fifo_stream_empty_n),
    .if_read(Loop_VITIS_LOOP_25_2_proc_U0_fifo_stream_read),
    .if_num_data_valid(fifo_stream_num_data_valid),
    .if_fifo_cap(fifo_stream_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_entry_proc_U0_ap_ready <= ap_sync_Block_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready <= ap_sync_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_loc6_channel <= 1'b0;
    end else begin
        if (((Block_entry_proc_U0_ap_done & Block_entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_loc6_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_loc6_channel <= ap_sync_channel_write_p_loc6_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_loc_channel <= 1'b0;
    end else begin
        if (((Block_entry_proc_U0_ap_done & Block_entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_loc_channel <= ap_sync_channel_write_p_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign Block_entry_proc_U0_ap_continue = (ap_sync_channel_write_p_loc_channel & ap_sync_channel_write_p_loc6_channel);

assign Block_entry_proc_U0_ap_start = ((ap_sync_reg_Block_entry_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign Loop_VITIS_LOOP_20_1_proc_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_20_1_proc_U0_ap_start = (p_loc_channel_empty_n & (ap_sync_reg_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign Loop_VITIS_LOOP_25_2_proc_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_25_2_proc_U0_ap_start = p_loc6_channel_empty_n;

assign ap_channel_done_p_loc6_channel = ((ap_sync_reg_channel_write_p_loc6_channel ^ 1'b1) & Block_entry_proc_U0_ap_done);

assign ap_channel_done_p_loc_channel = ((ap_sync_reg_channel_write_p_loc_channel ^ 1'b1) & Block_entry_proc_U0_ap_done);

assign ap_done = Loop_VITIS_LOOP_25_2_proc_U0_ap_done;

assign ap_idle = ((p_loc6_channel_empty_n ^ 1'b1) & (p_loc_channel_empty_n ^ 1'b1) & entry_proc_U0_ap_idle & Loop_VITIS_LOOP_25_2_proc_U0_ap_idle & Loop_VITIS_LOOP_20_1_proc_U0_ap_idle & Block_entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_entry_proc_U0_ap_ready = (ap_sync_reg_Block_entry_proc_U0_ap_ready | Block_entry_proc_U0_ap_ready);

assign ap_sync_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready = (ap_sync_reg_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready | Loop_VITIS_LOOP_20_1_proc_U0_ap_ready);

assign ap_sync_channel_write_p_loc6_channel = ((p_loc6_channel_full_n & ap_channel_done_p_loc6_channel) | ap_sync_reg_channel_write_p_loc6_channel);

assign ap_sync_channel_write_p_loc_channel = ((p_loc_channel_full_n & ap_channel_done_p_loc_channel) | ap_sync_reg_channel_write_p_loc_channel);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_Loop_VITIS_LOOP_20_1_proc_U0_ap_ready & ap_sync_Block_entry_proc_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign gmem0_0_RID = 1'd0;

assign gmem0_0_RLAST = 1'b0;

assign gmem0_0_RRESP = 2'd0;

assign gmem0_0_RUSER = 1'd0;

assign gmem1_0_BID = 1'd0;

assign gmem1_0_BRESP = 2'd0;

assign gmem1_0_BUSER = 1'd0;

endmodule //debug_fifo
