-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_accel_Block_entry_proc_Pipeline_VITIS_LOOP_99_1_VITIS_LOOP_100_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln99 : IN STD_LOGIC_VECTOR (62 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld : OUT STD_LOGIC;
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld : OUT STD_LOGIC;
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld : OUT STD_LOGIC;
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld : OUT STD_LOGIC;
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld : OUT STD_LOGIC;
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld : OUT STD_LOGIC;
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld : OUT STD_LOGIC;
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld : OUT STD_LOGIC;
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou : OUT STD_LOGIC_VECTOR (15 downto 0);
    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld : OUT STD_LOGIC );
end;


architecture behav of cnn_accel_Block_entry_proc_Pipeline_VITIS_LOOP_99_1_VITIS_LOOP_100_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln99_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_R : STD_LOGIC;
    signal icmp_ln10025_reg_194 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln100_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_icmp_ln10025_phi_fu_197_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal indvar_flatten4_fu_72 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln99_1_fu_272_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten4_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i5_fu_76 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal i_fu_264_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i5_load : STD_LOGIC_VECTOR (1 downto 0);
    signal j24_fu_80 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal j_fu_337_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_j24_load : STD_LOGIC_VECTOR (1 downto 0);
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fu_84 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal grp_fu_204_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_98_fu_88 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1010_fu_92 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1112_fu_96 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1214_fu_100 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1316_fu_104 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1418_fu_108 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1520_fu_112 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1622_fu_116 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln99_fu_258_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln100_fu_331_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i5_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                i5_fu_76 <= i_fu_264_p3;
            end if;
        end if;
    end process;

    indvar_flatten4_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                indvar_flatten4_fu_72 <= add_ln99_1_fu_272_p2;
            end if;
        end if;
    end process;

    j24_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                j24_fu_80 <= j_fu_337_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln99_fu_351_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                icmp_ln10025_reg_194 <= icmp_ln100_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((i_fu_264_p3 = ap_const_lv2_1)) and not((i_fu_264_p3 = ap_const_lv2_0)) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (grp_fu_204_p3 = ap_const_lv2_0))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1010_fu_92 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((grp_fu_204_p3 = ap_const_lv2_1)) and not((grp_fu_204_p3 = ap_const_lv2_0)) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (i_fu_264_p3 = ap_const_lv2_1))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1112_fu_96 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (grp_fu_204_p3 = ap_const_lv2_1) and (i_fu_264_p3 = ap_const_lv2_1))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1214_fu_100 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (grp_fu_204_p3 = ap_const_lv2_0) and (i_fu_264_p3 = ap_const_lv2_1))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1316_fu_104 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((grp_fu_204_p3 = ap_const_lv2_1)) and not((grp_fu_204_p3 = ap_const_lv2_0)) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (i_fu_264_p3 = ap_const_lv2_0))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1418_fu_108 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (grp_fu_204_p3 = ap_const_lv2_1) and (i_fu_264_p3 = ap_const_lv2_0))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1520_fu_112 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (grp_fu_204_p3 = ap_const_lv2_0) and (i_fu_264_p3 = ap_const_lv2_0))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1622_fu_116 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((i_fu_264_p3 = ap_const_lv2_1)) and not((i_fu_264_p3 = ap_const_lv2_0)) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (grp_fu_204_p3 = ap_const_lv2_1))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_98_fu_88 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((grp_fu_204_p3 = ap_const_lv2_1)) and not((grp_fu_204_p3 = ap_const_lv2_0)) and not((i_fu_264_p3 = ap_const_lv2_1)) and not((i_fu_264_p3 = ap_const_lv2_0)) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fu_84 <= m_axi_gmem_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln100_fu_331_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j24_load) + unsigned(ap_const_lv2_1));
    add_ln99_1_fu_272_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten4_load) + unsigned(ap_const_lv4_1));
    add_ln99_fu_258_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i5_load) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(m_axi_gmem_0_RVALID, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((m_axi_gmem_0_RVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2)
    begin
        if (((icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_icmp_ln10025_phi_fu_197_p4_assign_proc : process(ap_CS_fsm_state1, icmp_ln10025_reg_194, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_phi_mux_icmp_ln10025_phi_fu_197_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_icmp_ln10025_phi_fu_197_p4 <= icmp_ln10025_reg_194;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i5_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, i5_fu_76)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i5_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i5_load <= i5_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten4_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, indvar_flatten4_fu_72)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten4_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten4_load <= indvar_flatten4_fu_72;
        end if; 
    end process;


    ap_sig_allocacmp_j24_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, j24_fu_80)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j24_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_j24_load <= j24_fu_80;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fu_84;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_98_fu_88;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1010_fu_92;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1112_fu_96;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1214_fu_100;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1316_fu_104;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1418_fu_108;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1520_fu_112;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1622_fu_116;

    cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln99_fu_351_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln99_fu_351_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld <= ap_const_logic_1;
        else 
            cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_CS_fsm_state1, m_axi_gmem_0_RVALID, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_blk_n_R <= m_axi_gmem_0_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_204_p3 <= 
        ap_const_lv2_0 when (ap_phi_mux_icmp_ln10025_phi_fu_197_p4(0) = '1') else 
        ap_sig_allocacmp_j24_load;
    i_fu_264_p3 <= 
        add_ln99_fu_258_p2 when (ap_phi_mux_icmp_ln10025_phi_fu_197_p4(0) = '1') else 
        ap_sig_allocacmp_i5_load;
    icmp_ln100_fu_345_p2 <= "1" when (j_fu_337_p3 = ap_const_lv2_3) else "0";
    icmp_ln99_fu_351_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten4_load = ap_const_lv4_8) else "0";
    j_fu_337_p3 <= 
        ap_const_lv2_1 when (ap_phi_mux_icmp_ln10025_phi_fu_197_p4(0) = '1') else 
        add_ln100_fu_331_p2;
    m_axi_gmem_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_0_RREADY_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_gmem_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_0_WDATA <= ap_const_lv16_0;
    m_axi_gmem_0_WID <= ap_const_lv1_0;
    m_axi_gmem_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_0_WSTRB <= ap_const_lv2_0;
    m_axi_gmem_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_0_WVALID <= ap_const_logic_0;
end behav;
