-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_accel_load_input_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_11_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln10 : IN STD_LOGIC_VECTOR (62 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0 : OUT STD_LOGIC;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of cnn_accel_load_input_Pipeline_VITIS_LOOP_10_1_VITIS_LOOP_11_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv11_2B : STD_LOGIC_VECTOR (10 downto 0) := "00000101011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln10_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln10_1_fu_258_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln10_1_reg_410 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln11_fu_272_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_416 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_416_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_416_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_416_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_416_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_416_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_416_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln11_reg_416_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln_reg_420 : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_reg_420_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_reg_420_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_reg_420_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_reg_420_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_reg_420_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_reg_420_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_reg_420_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_425 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_425_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_425_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_425_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_425_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_425_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_425_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal gmem_addr_read_reg_431 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln13_2_fu_370_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_90 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln11_fu_286_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_94 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_fu_98 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln10_1_fu_226_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (9 downto 0);
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0_local : STD_LOGIC;
    signal trunc_ln10_fu_356_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0_local : STD_LOGIC;
    signal p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0_local : STD_LOGIC;
    signal icmp_ln11_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln10_fu_238_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_266_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_266_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln10_fu_250_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln10_fu_310_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln10_fu_310_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln10_fu_310_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_339_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_fu_332_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln13_fu_346_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_266_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln13_fu_350_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln13_1_fu_361_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln13_fu_364_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_266_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln10_fu_310_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component cnn_accel_urem_5ns_3ns_2_9_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component cnn_accel_mul_5ns_7ns_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component cnn_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_5ns_3ns_2_9_1_U14 : component cnn_accel_urem_5ns_3ns_2_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_266_p0,
        din1 => grp_fu_266_p1,
        ce => grp_fu_266_ce,
        dout => grp_fu_266_p2);

    mul_5ns_7ns_11_1_1_U15 : component cnn_accel_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln10_fu_310_p0,
        din1 => mul_ln10_fu_310_p1,
        dout => mul_ln10_fu_310_p2);

    flow_control_loop_pipe_sequential_init_U : component cnn_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    i_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln10_fu_220_p2 = ap_const_lv1_0))) then 
                    i_fu_94 <= select_ln10_1_fu_258_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_94 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln10_fu_220_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_98 <= add_ln10_1_fu_226_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_98 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln10_fu_220_p2 = ap_const_lv1_0))) then 
                    j_fu_90 <= add_ln11_fu_286_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_90 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                lshr_ln_reg_420 <= select_ln10_fu_250_p3(4 downto 1);
                lshr_ln_reg_420_pp0_iter1_reg <= lshr_ln_reg_420;
                select_ln10_1_reg_410 <= select_ln10_1_fu_258_p3;
                tmp_reg_425 <= mul_ln10_fu_310_p2(10 downto 7);
                trunc_ln11_reg_416 <= trunc_ln11_fu_272_p1;
                trunc_ln11_reg_416_pp0_iter1_reg <= trunc_ln11_reg_416;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                gmem_addr_read_reg_431 <= m_axi_gmem_0_RDATA;
                lshr_ln_reg_420_pp0_iter2_reg <= lshr_ln_reg_420_pp0_iter1_reg;
                lshr_ln_reg_420_pp0_iter3_reg <= lshr_ln_reg_420_pp0_iter2_reg;
                lshr_ln_reg_420_pp0_iter4_reg <= lshr_ln_reg_420_pp0_iter3_reg;
                lshr_ln_reg_420_pp0_iter5_reg <= lshr_ln_reg_420_pp0_iter4_reg;
                lshr_ln_reg_420_pp0_iter6_reg <= lshr_ln_reg_420_pp0_iter5_reg;
                lshr_ln_reg_420_pp0_iter7_reg <= lshr_ln_reg_420_pp0_iter6_reg;
                tmp_reg_425_pp0_iter2_reg <= tmp_reg_425;
                tmp_reg_425_pp0_iter3_reg <= tmp_reg_425_pp0_iter2_reg;
                tmp_reg_425_pp0_iter4_reg <= tmp_reg_425_pp0_iter3_reg;
                tmp_reg_425_pp0_iter5_reg <= tmp_reg_425_pp0_iter4_reg;
                tmp_reg_425_pp0_iter6_reg <= tmp_reg_425_pp0_iter5_reg;
                tmp_reg_425_pp0_iter7_reg <= tmp_reg_425_pp0_iter6_reg;
                trunc_ln11_reg_416_pp0_iter2_reg <= trunc_ln11_reg_416_pp0_iter1_reg;
                trunc_ln11_reg_416_pp0_iter3_reg <= trunc_ln11_reg_416_pp0_iter2_reg;
                trunc_ln11_reg_416_pp0_iter4_reg <= trunc_ln11_reg_416_pp0_iter3_reg;
                trunc_ln11_reg_416_pp0_iter5_reg <= trunc_ln11_reg_416_pp0_iter4_reg;
                trunc_ln11_reg_416_pp0_iter6_reg <= trunc_ln11_reg_416_pp0_iter5_reg;
                trunc_ln11_reg_416_pp0_iter7_reg <= trunc_ln11_reg_416_pp0_iter6_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln10_1_fu_226_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv10_1));
    add_ln10_fu_238_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv5_1));
    add_ln11_fu_286_p2 <= std_logic_vector(unsigned(select_ln10_fu_250_p3) + unsigned(ap_const_lv5_1));
    add_ln13_fu_364_p2 <= std_logic_vector(unsigned(sub_ln13_fu_350_p2) + unsigned(zext_ln13_1_fu_361_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_state8_pp0_stage0_iter7)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_state8_pp0_stage0_iter7)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7));
    end process;


    ap_block_state8_pp0_stage0_iter7_assign_proc : process(m_axi_gmem_0_RVALID)
    begin
                ap_block_state8_pp0_stage0_iter7 <= (m_axi_gmem_0_RVALID = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln10_fu_220_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln10_fu_220_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_94)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_94;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_98)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_98;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_90, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_90;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter7, m_axi_gmem_0_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem_blk_n_R <= m_axi_gmem_0_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_266_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_266_ce <= ap_const_logic_1;
        else 
            grp_fu_266_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_266_p0 <= 
        add_ln10_fu_238_p2 when (icmp_ln11_fu_244_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    grp_fu_266_p1 <= ap_const_lv5_3(3 - 1 downto 0);
    icmp_ln10_fu_220_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv10_310) else "0";
    icmp_ln11_fu_244_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv5_1C) else "0";
    m_axi_gmem_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_0_WDATA <= ap_const_lv16_0;
    m_axi_gmem_0_WID <= ap_const_lv1_0;
    m_axi_gmem_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_0_WSTRB <= ap_const_lv2_0;
    m_axi_gmem_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_0_WVALID <= ap_const_logic_0;
    mul_ln10_fu_310_p0 <= mul_ln10_fu_310_p00(5 - 1 downto 0);
    mul_ln10_fu_310_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_1_reg_410),11));
    mul_ln10_fu_310_p1 <= ap_const_lv11_2B(7 - 1 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_address0 <= zext_ln13_2_fu_370_p1(8 - 1 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_d0 <= gmem_addr_read_reg_431;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln11_reg_416_pp0_iter7_reg, trunc_ln10_fu_356_p1)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln10_fu_356_p1 = ap_const_lv2_0) and (trunc_ln11_reg_416_pp0_iter7_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_address0 <= zext_ln13_2_fu_370_p1(8 - 1 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_d0 <= gmem_addr_read_reg_431;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln11_reg_416_pp0_iter7_reg, trunc_ln10_fu_356_p1)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln10_fu_356_p1 = ap_const_lv2_1) and (trunc_ln11_reg_416_pp0_iter7_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_address0 <= zext_ln13_2_fu_370_p1(8 - 1 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_d0 <= gmem_addr_read_reg_431;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln11_reg_416_pp0_iter7_reg, trunc_ln10_fu_356_p1)
    begin
        if ((not((trunc_ln10_fu_356_p1 = ap_const_lv2_0)) and not((trunc_ln10_fu_356_p1 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln11_reg_416_pp0_iter7_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_address0 <= zext_ln13_2_fu_370_p1(8 - 1 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_d0 <= gmem_addr_read_reg_431;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln11_reg_416_pp0_iter7_reg, trunc_ln10_fu_356_p1)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln10_fu_356_p1 = ap_const_lv2_0) and (trunc_ln11_reg_416_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_address0 <= zext_ln13_2_fu_370_p1(8 - 1 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_d0 <= gmem_addr_read_reg_431;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln11_reg_416_pp0_iter7_reg, trunc_ln10_fu_356_p1)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln10_fu_356_p1 = ap_const_lv2_1) and (trunc_ln11_reg_416_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_address0 <= zext_ln13_2_fu_370_p1(8 - 1 downto 0);
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_d0 <= gmem_addr_read_reg_431;
    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0 <= p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0_local;

    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln11_reg_416_pp0_iter7_reg, trunc_ln10_fu_356_p1)
    begin
        if ((not((trunc_ln10_fu_356_p1 = ap_const_lv2_0)) and not((trunc_ln10_fu_356_p1 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln11_reg_416_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0_local <= ap_const_logic_1;
        else 
            p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_fu_332_p3 <= (tmp_reg_425_pp0_iter7_reg & ap_const_lv4_0);
    select_ln10_1_fu_258_p3 <= 
        add_ln10_fu_238_p2 when (icmp_ln11_fu_244_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln10_fu_250_p3 <= 
        ap_const_lv5_0 when (icmp_ln11_fu_244_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
    sub_ln13_fu_350_p2 <= std_logic_vector(unsigned(p_shl_fu_332_p3) - unsigned(zext_ln13_fu_346_p1));
    tmp_1_fu_339_p3 <= (tmp_reg_425_pp0_iter7_reg & ap_const_lv1_0);
    trunc_ln10_fu_356_p1 <= grp_fu_266_p2(2 - 1 downto 0);
    trunc_ln11_fu_272_p1 <= select_ln10_fu_250_p3(1 - 1 downto 0);
    zext_ln13_1_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_reg_420_pp0_iter7_reg),8));
    zext_ln13_2_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_fu_364_p2),64));
    zext_ln13_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_339_p3),8));
end behav;
