// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cnn_accel_cnn_accel,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=1715,HLS_SYN_TPT=833,HLS_SYN_MEM=18,HLS_SYN_DSP=0,HLS_SYN_FF=5379,HLS_SYN_LUT=5586,HLS_VERSION=2025_1}" *)

module cnn_accel (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] input_r;
wire   [63:0] kernel;
wire   [63:0] bias;
wire   [63:0] output_r;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem_0_AWREADY;
wire    gmem_0_WREADY;
wire    gmem_0_ARREADY;
wire    gmem_0_RVALID;
wire   [15:0] gmem_0_RDATA;
wire    gmem_0_RLAST;
wire   [0:0] gmem_0_RID;
wire   [9:0] gmem_0_RFIFONUM;
wire   [0:0] gmem_0_RUSER;
wire   [1:0] gmem_0_RRESP;
wire    gmem_0_BVALID;
wire   [1:0] gmem_0_BRESP;
wire   [0:0] gmem_0_BID;
wire   [0:0] gmem_0_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire   [63:0] entry_proc_U0_output_r_c_din;
wire    entry_proc_U0_output_r_c_write;
wire    Block_entry_proc_U0_ap_start;
wire    Block_entry_proc_U0_ap_done;
wire    Block_entry_proc_U0_ap_continue;
wire    Block_entry_proc_U0_ap_idle;
wire    Block_entry_proc_U0_ap_ready;
wire    Block_entry_proc_U0_m_axi_gmem_0_AWVALID;
wire   [63:0] Block_entry_proc_U0_m_axi_gmem_0_AWADDR;
wire   [0:0] Block_entry_proc_U0_m_axi_gmem_0_AWID;
wire   [31:0] Block_entry_proc_U0_m_axi_gmem_0_AWLEN;
wire   [2:0] Block_entry_proc_U0_m_axi_gmem_0_AWSIZE;
wire   [1:0] Block_entry_proc_U0_m_axi_gmem_0_AWBURST;
wire   [1:0] Block_entry_proc_U0_m_axi_gmem_0_AWLOCK;
wire   [3:0] Block_entry_proc_U0_m_axi_gmem_0_AWCACHE;
wire   [2:0] Block_entry_proc_U0_m_axi_gmem_0_AWPROT;
wire   [3:0] Block_entry_proc_U0_m_axi_gmem_0_AWQOS;
wire   [3:0] Block_entry_proc_U0_m_axi_gmem_0_AWREGION;
wire   [0:0] Block_entry_proc_U0_m_axi_gmem_0_AWUSER;
wire    Block_entry_proc_U0_m_axi_gmem_0_WVALID;
wire   [15:0] Block_entry_proc_U0_m_axi_gmem_0_WDATA;
wire   [1:0] Block_entry_proc_U0_m_axi_gmem_0_WSTRB;
wire    Block_entry_proc_U0_m_axi_gmem_0_WLAST;
wire   [0:0] Block_entry_proc_U0_m_axi_gmem_0_WID;
wire   [0:0] Block_entry_proc_U0_m_axi_gmem_0_WUSER;
wire    Block_entry_proc_U0_m_axi_gmem_0_ARVALID;
wire   [63:0] Block_entry_proc_U0_m_axi_gmem_0_ARADDR;
wire   [0:0] Block_entry_proc_U0_m_axi_gmem_0_ARID;
wire   [31:0] Block_entry_proc_U0_m_axi_gmem_0_ARLEN;
wire   [2:0] Block_entry_proc_U0_m_axi_gmem_0_ARSIZE;
wire   [1:0] Block_entry_proc_U0_m_axi_gmem_0_ARBURST;
wire   [1:0] Block_entry_proc_U0_m_axi_gmem_0_ARLOCK;
wire   [3:0] Block_entry_proc_U0_m_axi_gmem_0_ARCACHE;
wire   [2:0] Block_entry_proc_U0_m_axi_gmem_0_ARPROT;
wire   [3:0] Block_entry_proc_U0_m_axi_gmem_0_ARQOS;
wire   [3:0] Block_entry_proc_U0_m_axi_gmem_0_ARREGION;
wire   [0:0] Block_entry_proc_U0_m_axi_gmem_0_ARUSER;
wire    Block_entry_proc_U0_m_axi_gmem_0_RREADY;
wire    Block_entry_proc_U0_m_axi_gmem_0_BREADY;
wire   [7:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_address0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0;
wire   [15:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_d0;
wire   [7:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_address0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0;
wire   [15:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_d0;
wire   [7:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_address0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0;
wire   [15:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_d0;
wire   [7:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_address0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0;
wire   [15:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_d0;
wire   [7:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_address0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0;
wire   [15:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_d0;
wire   [7:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_address0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0;
wire   [15:0] Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_d0;
wire   [15:0] Block_entry_proc_U0_ap_return_0;
wire   [15:0] Block_entry_proc_U0_ap_return_1;
wire   [15:0] Block_entry_proc_U0_ap_return_2;
wire   [15:0] Block_entry_proc_U0_ap_return_3;
wire   [15:0] Block_entry_proc_U0_ap_return_4;
wire   [15:0] Block_entry_proc_U0_ap_return_5;
wire   [15:0] Block_entry_proc_U0_ap_return_6;
wire   [15:0] Block_entry_proc_U0_ap_return_7;
wire   [15:0] Block_entry_proc_U0_ap_return_8;
wire   [15:0] Block_entry_proc_U0_ap_return_9;
wire    ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_full_n;
reg    ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8;
wire    ap_sync_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8;
wire    ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input;
wire    Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_full_n;
reg    ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input;
wire    ap_sync_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input;
wire    conv_relu_U0_ap_start;
wire    conv_relu_U0_ap_done;
wire    conv_relu_U0_ap_continue;
wire    conv_relu_U0_ap_idle;
wire    conv_relu_U0_ap_ready;
wire   [8:0] conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_address0;
wire    conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_ce0;
wire    conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_we0;
wire   [14:0] conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_d0;
wire   [8:0] conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_address0;
wire    conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_ce0;
wire    conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_we0;
wire   [14:0] conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_d0;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_address0;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_ce0;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_address1;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_ce1;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_address0;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_ce0;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_address1;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_ce1;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_address0;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_ce0;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_address1;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_ce1;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_address0;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_ce0;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_address1;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_ce1;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_address0;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_ce0;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_address1;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_ce1;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_address0;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_ce0;
wire   [7:0] conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_address1;
wire    conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_ce1;
wire    ap_channel_done_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf;
wire    conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_full_n;
reg    ap_sync_reg_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf;
wire    ap_sync_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf;
wire    maxpool_U0_ap_start;
wire    maxpool_U0_ap_done;
wire    maxpool_U0_ap_continue;
wire    maxpool_U0_ap_idle;
wire    maxpool_U0_ap_ready;
wire    maxpool_U0_out_r_read;
wire    maxpool_U0_m_axi_gmem_0_AWVALID;
wire   [63:0] maxpool_U0_m_axi_gmem_0_AWADDR;
wire   [0:0] maxpool_U0_m_axi_gmem_0_AWID;
wire   [31:0] maxpool_U0_m_axi_gmem_0_AWLEN;
wire   [2:0] maxpool_U0_m_axi_gmem_0_AWSIZE;
wire   [1:0] maxpool_U0_m_axi_gmem_0_AWBURST;
wire   [1:0] maxpool_U0_m_axi_gmem_0_AWLOCK;
wire   [3:0] maxpool_U0_m_axi_gmem_0_AWCACHE;
wire   [2:0] maxpool_U0_m_axi_gmem_0_AWPROT;
wire   [3:0] maxpool_U0_m_axi_gmem_0_AWQOS;
wire   [3:0] maxpool_U0_m_axi_gmem_0_AWREGION;
wire   [0:0] maxpool_U0_m_axi_gmem_0_AWUSER;
wire    maxpool_U0_m_axi_gmem_0_WVALID;
wire   [15:0] maxpool_U0_m_axi_gmem_0_WDATA;
wire   [1:0] maxpool_U0_m_axi_gmem_0_WSTRB;
wire    maxpool_U0_m_axi_gmem_0_WLAST;
wire   [0:0] maxpool_U0_m_axi_gmem_0_WID;
wire   [0:0] maxpool_U0_m_axi_gmem_0_WUSER;
wire    maxpool_U0_m_axi_gmem_0_ARVALID;
wire   [63:0] maxpool_U0_m_axi_gmem_0_ARADDR;
wire   [0:0] maxpool_U0_m_axi_gmem_0_ARID;
wire   [31:0] maxpool_U0_m_axi_gmem_0_ARLEN;
wire   [2:0] maxpool_U0_m_axi_gmem_0_ARSIZE;
wire   [1:0] maxpool_U0_m_axi_gmem_0_ARBURST;
wire   [1:0] maxpool_U0_m_axi_gmem_0_ARLOCK;
wire   [3:0] maxpool_U0_m_axi_gmem_0_ARCACHE;
wire   [2:0] maxpool_U0_m_axi_gmem_0_ARPROT;
wire   [3:0] maxpool_U0_m_axi_gmem_0_ARQOS;
wire   [3:0] maxpool_U0_m_axi_gmem_0_ARREGION;
wire   [0:0] maxpool_U0_m_axi_gmem_0_ARUSER;
wire    maxpool_U0_m_axi_gmem_0_RREADY;
wire    maxpool_U0_m_axi_gmem_0_BREADY;
wire   [8:0] maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address0;
wire    maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0;
wire   [8:0] maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address1;
wire    maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1;
wire   [8:0] maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address0;
wire    maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0;
wire   [8:0] maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address1;
wire    maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_i_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_i_q1;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_t_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_t_q1;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_i_full_n;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_t_empty_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_i_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_i_q1;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_t_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_t_q1;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_i_full_n;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_t_empty_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_i_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_i_q1;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_t_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_t_q1;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_i_full_n;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_t_empty_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_i_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_i_q1;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_t_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_t_q1;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_i_full_n;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_t_empty_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_i_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_i_q1;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_t_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_t_q1;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_i_full_n;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_t_empty_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_i_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_i_q1;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_t_q0;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_t_q1;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_i_full_n;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_t_empty_n;
wire   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_i_q0;
wire   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_i_q1;
wire   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_t_q0;
wire   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_t_q1;
wire    cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_i_full_n;
wire    cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_t_empty_n;
wire   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_i_q0;
wire   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_i_q1;
wire   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_q0;
wire   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_q1;
wire    cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_i_full_n;
wire    cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_empty_n;
wire    output_r_c_full_n;
wire   [63:0] output_r_c_dout;
wire    output_r_c_empty_n;
wire   [2:0] output_r_c_num_data_valid;
wire   [2:0] output_r_c_fifo_cap;
wire    p_loc_channel_full_n;
wire   [15:0] p_loc_channel_dout;
wire    p_loc_channel_empty_n;
wire   [2:0] p_loc_channel_num_data_valid;
wire   [2:0] p_loc_channel_fifo_cap;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_full_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fifo_cap;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_full_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_fifo_cap;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_full_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_fifo_cap;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_full_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_fifo_cap;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_full_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_fifo_cap;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_full_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_fifo_cap;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_full_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_fifo_cap;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_full_n;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_fifo_cap;
wire   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_dout;
wire    p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_empty_n;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_num_data_valid;
wire   [2:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_fifo_cap;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_Block_entry_proc_U0_ap_ready;
wire    ap_sync_Block_entry_proc_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8 = 1'b0;
#0 ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input = 1'b0;
#0 ap_sync_reg_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Block_entry_proc_U0_ap_ready = 1'b0;
end

cnn_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .kernel(kernel),
    .bias(bias),
    .output_r(output_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cnn_accel_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(Block_entry_proc_U0_m_axi_gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(Block_entry_proc_U0_m_axi_gmem_0_ARADDR),
    .I_CH0_ARLEN(Block_entry_proc_U0_m_axi_gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(Block_entry_proc_U0_m_axi_gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(maxpool_U0_m_axi_gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(maxpool_U0_m_axi_gmem_0_AWADDR),
    .I_CH0_AWLEN(maxpool_U0_m_axi_gmem_0_AWLEN),
    .I_CH0_WVALID(maxpool_U0_m_axi_gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(maxpool_U0_m_axi_gmem_0_WDATA),
    .I_CH0_WSTRB(maxpool_U0_m_axi_gmem_0_WSTRB),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(maxpool_U0_m_axi_gmem_0_BREADY)
);

cnn_accel_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .output_r(output_r),
    .output_r_c_din(entry_proc_U0_output_r_c_din),
    .output_r_c_full_n(output_r_c_full_n),
    .output_r_c_write(entry_proc_U0_output_r_c_write),
    .output_r_c_num_data_valid(output_r_c_num_data_valid),
    .output_r_c_fifo_cap(output_r_c_fifo_cap)
);

cnn_accel_Block_entry_proc Block_entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry_proc_U0_ap_start),
    .ap_done(Block_entry_proc_U0_ap_done),
    .ap_continue(Block_entry_proc_U0_ap_continue),
    .ap_idle(Block_entry_proc_U0_ap_idle),
    .ap_ready(Block_entry_proc_U0_ap_ready),
    .kernel(kernel),
    .bias(bias),
    .m_axi_gmem_0_AWVALID(Block_entry_proc_U0_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(Block_entry_proc_U0_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(Block_entry_proc_U0_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(Block_entry_proc_U0_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(Block_entry_proc_U0_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(Block_entry_proc_U0_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(Block_entry_proc_U0_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(Block_entry_proc_U0_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(Block_entry_proc_U0_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(Block_entry_proc_U0_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(Block_entry_proc_U0_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(Block_entry_proc_U0_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(Block_entry_proc_U0_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(Block_entry_proc_U0_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(Block_entry_proc_U0_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(Block_entry_proc_U0_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(Block_entry_proc_U0_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(Block_entry_proc_U0_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(Block_entry_proc_U0_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(Block_entry_proc_U0_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(Block_entry_proc_U0_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(Block_entry_proc_U0_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(Block_entry_proc_U0_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(Block_entry_proc_U0_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(Block_entry_proc_U0_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(Block_entry_proc_U0_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(Block_entry_proc_U0_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(Block_entry_proc_U0_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(Block_entry_proc_U0_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(Block_entry_proc_U0_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(Block_entry_proc_U0_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(gmem_0_RLAST),
    .m_axi_gmem_0_RID(gmem_0_RID),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(gmem_0_RUSER),
    .m_axi_gmem_0_RRESP(gmem_0_RRESP),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(Block_entry_proc_U0_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .input_r(input_r),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_d0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_d0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_d0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_d0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_d0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_d0),
    .ap_return_0(Block_entry_proc_U0_ap_return_0),
    .ap_return_1(Block_entry_proc_U0_ap_return_1),
    .ap_return_2(Block_entry_proc_U0_ap_return_2),
    .ap_return_3(Block_entry_proc_U0_ap_return_3),
    .ap_return_4(Block_entry_proc_U0_ap_return_4),
    .ap_return_5(Block_entry_proc_U0_ap_return_5),
    .ap_return_6(Block_entry_proc_U0_ap_return_6),
    .ap_return_7(Block_entry_proc_U0_ap_return_7),
    .ap_return_8(Block_entry_proc_U0_ap_return_8),
    .ap_return_9(Block_entry_proc_U0_ap_return_9)
);

cnn_accel_conv_relu conv_relu_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_relu_U0_ap_start),
    .ap_done(conv_relu_U0_ap_done),
    .ap_continue(conv_relu_U0_ap_continue),
    .ap_idle(conv_relu_U0_ap_idle),
    .ap_ready(conv_relu_U0_ap_ready),
    .p_read(p_loc_channel_dout),
    .p_read1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_dout),
    .p_read2(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_dout),
    .p_read3(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_dout),
    .p_read4(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_dout),
    .p_read5(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_dout),
    .p_read6(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_dout),
    .p_read7(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_dout),
    .p_read8(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_dout),
    .p_read9(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_dout),
    .cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_address0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_address0),
    .cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_ce0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_ce0),
    .cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_we0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_we0),
    .cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_d0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_d0),
    .cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_address0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_address0),
    .cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_ce0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_ce0),
    .cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_we0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_we0),
    .cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_d0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_d0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_t_q0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_address1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_ce1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_t_q1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_t_q0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_address1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_ce1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_t_q1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_t_q0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_address1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_ce1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_t_q1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_t_q0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_address1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_ce1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_t_q1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_t_q0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_address1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_ce1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_t_q1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_address0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_ce0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_t_q0),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_address1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_ce1),
    .p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_t_q1)
);

cnn_accel_maxpool maxpool_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(maxpool_U0_ap_start),
    .ap_done(maxpool_U0_ap_done),
    .ap_continue(maxpool_U0_ap_continue),
    .ap_idle(maxpool_U0_ap_idle),
    .ap_ready(maxpool_U0_ap_ready),
    .out_r_dout(output_r_c_dout),
    .out_r_empty_n(output_r_c_empty_n),
    .out_r_read(maxpool_U0_out_r_read),
    .out_r_num_data_valid(output_r_c_num_data_valid),
    .out_r_fifo_cap(output_r_c_fifo_cap),
    .m_axi_gmem_0_AWVALID(maxpool_U0_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(maxpool_U0_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(maxpool_U0_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(maxpool_U0_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(maxpool_U0_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(maxpool_U0_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(maxpool_U0_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(maxpool_U0_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(maxpool_U0_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(maxpool_U0_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(maxpool_U0_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(maxpool_U0_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(maxpool_U0_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(maxpool_U0_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(maxpool_U0_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(maxpool_U0_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(maxpool_U0_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(maxpool_U0_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(maxpool_U0_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(1'b0),
    .m_axi_gmem_0_ARADDR(maxpool_U0_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(maxpool_U0_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(maxpool_U0_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(maxpool_U0_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(maxpool_U0_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(maxpool_U0_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(maxpool_U0_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(maxpool_U0_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(maxpool_U0_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(maxpool_U0_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(maxpool_U0_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(1'b0),
    .m_axi_gmem_0_RREADY(maxpool_U0_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(16'd0),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(10'd0),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(maxpool_U0_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(gmem_0_BRESP),
    .m_axi_gmem_0_BID(gmem_0_BID),
    .m_axi_gmem_0_BUSER(gmem_0_BUSER),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address0(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address0),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q0(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_t_q0),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address1(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address1),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q1(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_t_q1),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address0(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address0),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q0(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_q0),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address1(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address1),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1),
    .cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q1(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_q1)
);

cnn_accel_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9ibkb #(
    .DataWidth( 16 ),
    .AddressRange( 140 ),
    .AddressWidth( 8 ))
p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_address0),
    .i_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_ce0),
    .i_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_we0),
    .i_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_0_d0),
    .i_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_i_q1),
    .t_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_address0),
    .t_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_t_q0),
    .t_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_address1),
    .t_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_ce1),
    .t_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_i_full_n),
    .i_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input),
    .t_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_5_t_empty_n),
    .t_read(conv_relu_U0_ap_ready)
);

cnn_accel_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9ibkb #(
    .DataWidth( 16 ),
    .AddressRange( 140 ),
    .AddressWidth( 8 ))
p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_address0),
    .i_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_ce0),
    .i_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_we0),
    .i_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_1_d0),
    .i_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_i_q1),
    .t_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_address0),
    .t_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_t_q0),
    .t_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_address1),
    .t_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_ce1),
    .t_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_i_full_n),
    .i_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input),
    .t_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_4_t_empty_n),
    .t_read(conv_relu_U0_ap_ready)
);

cnn_accel_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9ibkb #(
    .DataWidth( 16 ),
    .AddressRange( 140 ),
    .AddressWidth( 8 ))
p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_address0),
    .i_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_ce0),
    .i_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_we0),
    .i_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_0_2_d0),
    .i_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_i_q1),
    .t_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_address0),
    .t_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_t_q0),
    .t_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_address1),
    .t_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_ce1),
    .t_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_i_full_n),
    .i_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input),
    .t_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_3_t_empty_n),
    .t_read(conv_relu_U0_ap_ready)
);

cnn_accel_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9ibkb #(
    .DataWidth( 16 ),
    .AddressRange( 140 ),
    .AddressWidth( 8 ))
p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_address0),
    .i_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_ce0),
    .i_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_we0),
    .i_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_0_d0),
    .i_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_i_q1),
    .t_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_address0),
    .t_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_t_q0),
    .t_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_address1),
    .t_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_ce1),
    .t_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_i_full_n),
    .i_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input),
    .t_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_2_t_empty_n),
    .t_read(conv_relu_U0_ap_ready)
);

cnn_accel_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9ibkb #(
    .DataWidth( 16 ),
    .AddressRange( 140 ),
    .AddressWidth( 8 ))
p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_address0),
    .i_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_ce0),
    .i_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_we0),
    .i_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_1_d0),
    .i_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_i_q1),
    .t_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_address0),
    .t_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_t_q0),
    .t_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_address1),
    .t_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_ce1),
    .t_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_i_full_n),
    .i_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input),
    .t_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_1_t_empty_n),
    .t_read(conv_relu_U0_ap_ready)
);

cnn_accel_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9ibkb #(
    .DataWidth( 16 ),
    .AddressRange( 140 ),
    .AddressWidth( 8 ))
p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_address0),
    .i_ce0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_ce0),
    .i_we0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_we0),
    .i_d0(Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_d0),
    .i_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_i_q0),
    .i_address1(8'd0),
    .i_ce1(1'b0),
    .i_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_i_q1),
    .t_address0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_address0),
    .t_ce0(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_t_q0),
    .t_address1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_address1),
    .t_ce1(conv_relu_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_ce1),
    .t_q1(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_i_full_n),
    .i_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input),
    .t_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_t_empty_n),
    .t_read(conv_relu_U0_ap_ready)
);

cnn_accel_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_RAM_AUTO_hbi #(
    .DataWidth( 15 ),
    .AddressRange( 338 ),
    .AddressWidth( 9 ))
cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_address0),
    .i_ce0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_ce0),
    .i_we0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_we0),
    .i_d0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_d0),
    .i_q0(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_i_q1),
    .t_address0(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address0),
    .t_ce0(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0),
    .t_we0(1'b0),
    .t_d0(15'd0),
    .t_q0(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_t_q0),
    .t_address1(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address1),
    .t_ce1(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1),
    .t_q1(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_i_full_n),
    .i_write(ap_channel_done_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf),
    .t_empty_n(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_t_empty_n),
    .t_read(maxpool_U0_ap_ready)
);

cnn_accel_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_RAM_AUTO_hbi #(
    .DataWidth( 15 ),
    .AddressRange( 338 ),
    .AddressWidth( 9 ))
cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_address0),
    .i_ce0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_ce0),
    .i_we0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_we0),
    .i_d0(conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_d0),
    .i_q0(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_i_q1),
    .t_address0(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address0),
    .t_ce0(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0),
    .t_we0(1'b0),
    .t_d0(15'd0),
    .t_q0(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_q0),
    .t_address1(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address1),
    .t_ce1(maxpool_U0_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1),
    .t_q1(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_i_full_n),
    .i_write(ap_channel_done_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf),
    .t_empty_n(cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_empty_n),
    .t_read(maxpool_U0_ap_ready)
);

cnn_accel_fifo_w64_d4_S output_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_output_r_c_din),
    .if_full_n(output_r_c_full_n),
    .if_write(entry_proc_U0_output_r_c_write),
    .if_dout(output_r_c_dout),
    .if_empty_n(output_r_c_empty_n),
    .if_read(maxpool_U0_out_r_read),
    .if_num_data_valid(output_r_c_num_data_valid),
    .if_fifo_cap(output_r_c_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_0),
    .if_full_n(p_loc_channel_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_loc_channel_dout),
    .if_empty_n(p_loc_channel_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_loc_channel_num_data_valid),
    .if_fifo_cap(p_loc_channel_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_1),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_2),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_3),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_2_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_4),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_3_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_5),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_4_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_6),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_5_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_7),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_6_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_8),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_7_fifo_cap)
);

cnn_accel_fifo_w16_d2_S p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry_proc_U0_ap_return_9),
    .if_full_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_full_n),
    .if_write(ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8),
    .if_dout(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_dout),
    .if_empty_n(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_empty_n),
    .if_read(conv_relu_U0_ap_ready),
    .if_num_data_valid(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_num_data_valid),
    .if_fifo_cap(p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_entry_proc_U0_ap_ready <= ap_sync_Block_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf <= 1'b0;
    end else begin
        if (((conv_relu_U0_ap_done & conv_relu_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf <= ap_sync_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8 <= 1'b0;
    end else begin
        if (((Block_entry_proc_U0_ap_done & Block_entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8 <= ap_sync_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input <= 1'b0;
    end else begin
        if (((Block_entry_proc_U0_ap_done & Block_entry_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input <= ap_sync_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign Block_entry_proc_U0_ap_continue = ap_sync_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input;

assign Block_entry_proc_U0_ap_start = ((ap_sync_reg_Block_entry_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_full_n = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_i_full_n;

assign ap_channel_done_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf = ((ap_sync_reg_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf ^ 1'b1) & conv_relu_U0_ap_done);

assign ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8 = ((ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8 ^ 1'b1) & Block_entry_proc_U0_ap_done);

assign ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input = ((ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input ^ 1'b1) & Block_entry_proc_U0_ap_done);

assign ap_done = maxpool_U0_ap_done;

assign ap_idle = (maxpool_U0_ap_idle & (p_loc_channel_empty_n ^ 1'b1) & (cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_empty_n ^ 1'b1) & entry_proc_U0_ap_idle & conv_relu_U0_ap_idle & Block_entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_entry_proc_U0_ap_ready = (ap_sync_reg_Block_entry_proc_U0_ap_ready | Block_entry_proc_U0_ap_ready);

assign ap_sync_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf = ((conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_full_n & ap_channel_done_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf) | ap_sync_reg_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf);

assign ap_sync_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8 = ((p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8_full_n & ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8) | ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_8);

assign ap_sync_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input = ((ap_channel_done_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input & Block_entry_proc_U0_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input_buf_1_2_full_n) | ap_sync_reg_channel_write_p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E9input);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_Block_entry_proc_U0_ap_ready);

assign conv_relu_U0_ap_continue = ap_sync_channel_write_cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf;

assign conv_relu_U0_ap_start = p_loc_channel_empty_n;

assign conv_relu_U0_cnn_accel_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_conv_buf_1_full_n = cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_i_full_n;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign gmem_0_BID = 1'd0;

assign gmem_0_BRESP = 2'd0;

assign gmem_0_BUSER = 1'd0;

assign gmem_0_RID = 1'd0;

assign gmem_0_RLAST = 1'b0;

assign gmem_0_RRESP = 2'd0;

assign gmem_0_RUSER = 1'd0;

assign maxpool_U0_ap_continue = 1'b1;

assign maxpool_U0_ap_start = cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_t_empty_n;

endmodule //cnn_accel
