// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_Block_entry_proc_Pipeline_VITIS_LOOP_99_1_VITIS_LOOP_100_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        sext_ln99,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou,
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [15:0] m_axi_gmem_0_WDATA;
output  [1:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [15:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [9:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [62:0] sext_ln99;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld;
output  [15:0] cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou;
output   cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld;

reg ap_idle;
reg m_axi_gmem_0_RREADY;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld;
reg cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln99_fu_351_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_R;
reg   [0:0] icmp_ln10025_reg_194;
wire   [0:0] icmp_ln100_fu_345_p2;
reg   [0:0] ap_phi_mux_icmp_ln10025_phi_fu_197_p4;
wire    ap_loop_init;
reg   [3:0] indvar_flatten4_fu_72;
wire   [3:0] add_ln99_1_fu_272_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten4_load;
reg   [1:0] i5_fu_76;
wire   [1:0] i_fu_264_p3;
reg   [1:0] ap_sig_allocacmp_i5_load;
reg   [1:0] j24_fu_80;
wire   [1:0] j_fu_337_p3;
reg   [1:0] ap_sig_allocacmp_j24_load;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fu_84;
wire   [1:0] grp_fu_204_p3;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_98_fu_88;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1010_fu_92;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1112_fu_96;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1214_fu_100;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1316_fu_104;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1418_fu_108;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1520_fu_112;
reg   [15:0] p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1622_fu_116;
wire   [1:0] add_ln99_fu_258_p2;
wire   [1:0] add_ln100_fu_331_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 indvar_flatten4_fu_72 = 4'd0;
#0 i5_fu_76 = 2'd0;
#0 j24_fu_80 = 2'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fu_84 = 16'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_98_fu_88 = 16'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1010_fu_92 = 16'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1112_fu_96 = 16'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1214_fu_100 = 16'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1316_fu_104 = 16'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1418_fu_108 = 16'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1520_fu_112 = 16'd0;
#0 p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1622_fu_116 = 16'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i5_fu_76 <= i_fu_264_p3;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
    indvar_flatten4_fu_72 <= add_ln99_1_fu_272_p2;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
    j24_fu_80 <= j_fu_337_p3;
end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln99_fu_351_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln10025_reg_194 <= icmp_ln100_fu_345_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_fu_264_p3 == 2'd1) & ~(i_fu_264_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (grp_fu_204_p3 == 2'd0))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1010_fu_92 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(grp_fu_204_p3 == 2'd1) & ~(grp_fu_204_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_fu_264_p3 == 2'd1))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1112_fu_96 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (grp_fu_204_p3 == 2'd1) & (i_fu_264_p3 == 2'd1))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1214_fu_100 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (grp_fu_204_p3 == 2'd0) & (i_fu_264_p3 == 2'd1))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1316_fu_104 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(grp_fu_204_p3 == 2'd1) & ~(grp_fu_204_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_fu_264_p3 == 2'd0))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1418_fu_108 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (grp_fu_204_p3 == 2'd1) & (i_fu_264_p3 == 2'd0))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1520_fu_112 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (grp_fu_204_p3 == 2'd0) & (i_fu_264_p3 == 2'd0))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1622_fu_116 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_fu_264_p3 == 2'd1) & ~(i_fu_264_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (grp_fu_204_p3 == 2'd1))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_98_fu_88 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(grp_fu_204_p3 == 2'd1) & ~(grp_fu_204_p3 == 2'd0) & ~(i_fu_264_p3 == 2'd1) & ~(i_fu_264_p3 == 2'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fu_84 <= m_axi_gmem_0_RDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_phi_mux_icmp_ln10025_phi_fu_197_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln10025_phi_fu_197_p4 = icmp_ln10025_reg_194;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i5_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i5_load = i5_fu_76;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten4_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten4_load = indvar_flatten4_fu_72;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j24_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j24_load = j24_fu_80;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln99_fu_351_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld = 1'b1;
    end else begin
        cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_fu_331_p2 = (ap_sig_allocacmp_j24_load + 2'd1);

assign add_ln99_1_fu_272_p2 = (ap_sig_allocacmp_indvar_flatten4_load + 4'd1);

assign add_ln99_fu_258_p2 = (ap_sig_allocacmp_i5_load + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((m_axi_gmem_0_RVALID == 1'b0) | (ap_start_int == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_17_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_fu_84;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_18_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_98_fu_88;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_19_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1010_fu_92;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_20_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1112_fu_96;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_21_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1214_fu_100;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_22_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1316_fu_104;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_23_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1418_fu_108;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_24_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1520_fu_112;

assign cnn_accel_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_ap_fixed_16_8_ap_q_mode_5_ap_o_mode_3_0_kern_25_ou = p_ZZ9cnn_accelP8ap_fixedILi16ELi8EL9ap_q_mode5EL9ap_o_mode3ELi0EES3_S3_S3_E10kern_1622_fu_116;

assign grp_fu_204_p3 = ((ap_phi_mux_icmp_ln10025_phi_fu_197_p4[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j24_load);

assign i_fu_264_p3 = ((ap_phi_mux_icmp_ln10025_phi_fu_197_p4[0:0] == 1'b1) ? add_ln99_fu_258_p2 : ap_sig_allocacmp_i5_load);

assign icmp_ln100_fu_345_p2 = ((j_fu_337_p3 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_351_p2 = ((ap_sig_allocacmp_indvar_flatten4_load == 4'd8) ? 1'b1 : 1'b0);

assign j_fu_337_p3 = ((ap_phi_mux_icmp_ln10025_phi_fu_197_p4[0:0] == 1'b1) ? 2'd1 : add_ln100_fu_331_p2);

assign m_axi_gmem_0_ARADDR = 64'd0;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 32'd0;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_ARVALID = 1'b0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 16'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 2'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

endmodule //cnn_accel_Block_entry_proc_Pipeline_VITIS_LOOP_99_1_VITIS_LOOP_100_2
