// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accel_maxpool (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        out_r_dout,
        out_r_empty_n,
        out_r_read,
        out_r_num_data_valid,
        out_r_fifo_cap,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address0,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q0,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address1,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q1,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address0,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q0,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address1,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1,
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] out_r_dout;
input   out_r_empty_n;
output   out_r_read;
input  [2:0] out_r_num_data_valid;
input  [2:0] out_r_fifo_cap;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [15:0] m_axi_gmem_0_WDATA;
output  [1:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [15:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [9:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
output  [8:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address0;
output   cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0;
input  [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q0;
output  [8:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address1;
output   cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1;
input  [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q1;
output  [8:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address0;
output   cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0;
input  [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q0;
output  [8:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address1;
output   cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1;
input  [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q1;

reg ap_idle;
reg out_r_read;
reg m_axi_gmem_0_AWVALID;
reg m_axi_gmem_0_WVALID;
reg m_axi_gmem_0_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] first_iter_0_reg_174;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg   [0:0] first_iter_0_reg_174_pp0_iter1_reg;
reg    ap_block_state3_io_grp1;
reg   [0:0] icmp_ln61_reg_457;
reg   [0:0] icmp_ln61_reg_457_pp0_iter10_reg;
reg    ap_block_state12_pp0_stage0_iter11_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln61_fu_284_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
reg    ap_block_pp0_stage0_11001;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg;
reg    ap_loop_exit_ready_delayed;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage0_grp1;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg    out_r_blk_n;
reg    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0;
wire   [3:0] select_ln61_fu_226_p3;
reg   [3:0] select_ln61_reg_437;
reg   [3:0] select_ln61_reg_437_pp0_iter1_reg;
wire   [0:0] icmp_ln62_fu_278_p2;
reg   [0:0] icmp_ln62_reg_452;
reg   [0:0] icmp_ln61_reg_457_pp0_iter1_reg;
reg   [0:0] icmp_ln61_reg_457_pp0_iter2_reg;
reg   [0:0] icmp_ln61_reg_457_pp0_iter3_reg;
reg   [0:0] icmp_ln61_reg_457_pp0_iter4_reg;
reg   [0:0] icmp_ln61_reg_457_pp0_iter5_reg;
reg   [0:0] icmp_ln61_reg_457_pp0_iter6_reg;
reg   [0:0] icmp_ln61_reg_457_pp0_iter7_reg;
reg   [0:0] icmp_ln61_reg_457_pp0_iter8_reg;
reg   [0:0] icmp_ln61_reg_457_pp0_iter9_reg;
reg   [63:0] gmem_addr_reg_461;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [8:0] zext_ln64_2_fu_333_p1;
wire   [14:0] maxv_1_fu_358_p3;
reg   [14:0] maxv_1_reg_498;
reg   [14:0] maxv_2_reg_504;
reg   [14:0] cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_load_1_reg_510;
wire   [14:0] maxv_4_fu_381_p3;
reg   [14:0] maxv_4_reg_516;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_icmp_ln6228_phi_fu_189_p4;
wire   [63:0] zext_ln64_3_fu_342_p1;
wire   [63:0] zext_ln67_1_fu_347_p1;
wire  signed [63:0] sext_ln61_fu_315_p1;
reg    ap_block_pp0_stage0_01001_grp1;
reg   [7:0] indvar_flatten25_fu_82;
wire   [7:0] add_ln61_1_fu_272_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten25_load;
reg   [3:0] i26_fu_86;
wire   [3:0] i_fu_234_p3;
reg   [3:0] ap_sig_allocacmp_i26_load;
reg   [3:0] j27_fu_90;
wire   [3:0] j_fu_266_p2;
reg   [3:0] ap_sig_allocacmp_j27_load;
reg    cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1_local;
reg    cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0_local;
reg    cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1_local;
reg    cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0_local;
wire   [3:0] add_ln61_fu_220_p2;
wire   [4:0] tmp_fu_242_p3;
wire   [4:0] tmp_1_fu_254_p3;
wire   [62:0] trunc_ln_fu_305_p4;
wire   [8:0] grp_fu_392_p3;
wire   [8:0] grp_fu_401_p3;
wire   [0:0] icmp_ln66_fu_352_p2;
wire   [0:0] icmp_ln67_fu_366_p2;
wire   [14:0] maxv_3_fu_370_p3;
wire   [0:0] icmp_ln68_fu_376_p2;
wire   [4:0] grp_fu_392_p0;
wire   [3:0] grp_fu_392_p1;
wire   [3:0] grp_fu_392_p2;
wire   [4:0] grp_fu_401_p0;
wire   [3:0] grp_fu_401_p1;
wire   [3:0] grp_fu_401_p2;
reg    grp_fu_392_ce;
reg    grp_fu_401_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [8:0] grp_fu_392_p00;
wire   [8:0] grp_fu_401_p00;
reg    ap_condition_536;
reg    ap_condition_541;
reg    ap_condition_249;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 indvar_flatten25_fu_82 = 8'd0;
#0 i26_fu_86 = 4'd0;
#0 j27_fu_90 = 4'd0;
end

cnn_accel_mac_muladd_5ns_4ns_4ns_9_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 9 ))
mac_muladd_5ns_4ns_4ns_9_4_1_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_392_p0),
    .din1(grp_fu_392_p1),
    .din2(grp_fu_392_p2),
    .ce(grp_fu_392_ce),
    .dout(grp_fu_392_p3)
);

cnn_accel_mac_muladd_5ns_4ns_4ns_9_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 9 ))
mac_muladd_5ns_4ns_4ns_9_4_1_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_401_p0),
    .din1(grp_fu_401_p1),
    .din2(grp_fu_401_p2),
    .ce(grp_fu_401_ce),
    .dout(grp_fu_401_p3)
);

cnn_accel_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_541)) begin
            first_iter_0_reg_174 <= 1'd0;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            first_iter_0_reg_174 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_249)) begin
        i26_fu_86 <= i_fu_234_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_249)) begin
    indvar_flatten25_fu_82 <= add_ln61_1_fu_272_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_249)) begin
    j27_fu_90 <= j_fu_266_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_0_reg_174_pp0_iter1_reg <= first_iter_0_reg_174;
        icmp_ln61_reg_457 <= icmp_ln61_fu_284_p2;
        icmp_ln61_reg_457_pp0_iter1_reg <= icmp_ln61_reg_457;
        select_ln61_reg_437 <= select_ln61_fu_226_p3;
        select_ln61_reg_437_pp0_iter1_reg <= select_ln61_reg_437;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln61_reg_457_pp0_iter10_reg <= icmp_ln61_reg_457_pp0_iter9_reg;
        icmp_ln61_reg_457_pp0_iter2_reg <= icmp_ln61_reg_457_pp0_iter1_reg;
        icmp_ln61_reg_457_pp0_iter3_reg <= icmp_ln61_reg_457_pp0_iter2_reg;
        icmp_ln61_reg_457_pp0_iter4_reg <= icmp_ln61_reg_457_pp0_iter3_reg;
        icmp_ln61_reg_457_pp0_iter5_reg <= icmp_ln61_reg_457_pp0_iter4_reg;
        icmp_ln61_reg_457_pp0_iter6_reg <= icmp_ln61_reg_457_pp0_iter5_reg;
        icmp_ln61_reg_457_pp0_iter7_reg <= icmp_ln61_reg_457_pp0_iter6_reg;
        icmp_ln61_reg_457_pp0_iter8_reg <= icmp_ln61_reg_457_pp0_iter7_reg;
        icmp_ln61_reg_457_pp0_iter9_reg <= icmp_ln61_reg_457_pp0_iter8_reg;
        maxv_1_reg_498 <= maxv_1_fu_358_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_load_1_reg_510 <= cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q0;
        maxv_2_reg_504 <= cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        gmem_addr_reg_461 <= sext_ln61_fu_315_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln62_reg_452 <= icmp_ln62_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        maxv_4_reg_516 <= maxv_4_fu_381_p3;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln61_fu_284_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_536)) begin
            ap_phi_mux_icmp_ln6228_phi_fu_189_p4 = icmp_ln62_reg_452;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln6228_phi_fu_189_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln6228_phi_fu_189_p4 = icmp_ln62_reg_452;
        end
    end else begin
        ap_phi_mux_icmp_ln6228_phi_fu_189_p4 = icmp_ln62_reg_452;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i26_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i26_load = i26_fu_86;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten25_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten25_load = indvar_flatten25_fu_82;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j27_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j27_load = j27_fu_90;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0_local = 1'b1;
    end else begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1_local = 1'b1;
    end else begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0_local = 1'b1;
    end else begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1_local = 1'b1;
    end else begin
        cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (first_iter_0_reg_174_pp0_iter1_reg == 1'd1))) begin
        gmem_blk_n_AW = m_axi_gmem_0_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln61_reg_457_pp0_iter10_reg == 1'd1))) begin
        gmem_blk_n_B = m_axi_gmem_0_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_blk_n_W = m_axi_gmem_0_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_392_ce = 1'b1;
    end else begin
        grp_fu_392_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_401_ce = 1'b1;
    end else begin
        grp_fu_401_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (first_iter_0_reg_174_pp0_iter1_reg == 1'd1))) begin
        m_axi_gmem_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln61_reg_457_pp0_iter10_reg == 1'd1))) begin
        m_axi_gmem_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1) & (first_iter_0_reg_174 == 1'd1))) begin
        out_r_blk_n = out_r_empty_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (first_iter_0_reg_174 == 1'd1))) begin
        out_r_read = 1'b1;
    end else begin
        out_r_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln61_1_fu_272_p2 = (ap_sig_allocacmp_indvar_flatten25_load + 8'd1);

assign add_ln61_fu_220_p2 = (ap_sig_allocacmp_i26_load + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_grp1)) | ((m_axi_gmem_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp0 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_grp1)) | ((m_axi_gmem_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11_grp1)) | ((m_axi_gmem_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_io_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = ((ap_done_reg == 1'b1) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11_grp1 = ((icmp_ln61_reg_457_pp0_iter10_reg == 1'd1) & (m_axi_gmem_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((out_r_empty_n == 1'b0) & (first_iter_0_reg_174 == 1'd1));
end

always @ (*) begin
    ap_block_state3_io_grp1 = ((m_axi_gmem_0_AWREADY == 1'b0) & (first_iter_0_reg_174_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_condition_249 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_536 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln61_reg_457 == 1'd0));
end

always @ (*) begin
    ap_condition_541 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln61_reg_457 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address0 = zext_ln67_1_fu_347_p1;

assign cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_address1 = zext_ln64_3_fu_342_p1;

assign cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0 = cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce0_local;

assign cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1 = cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_ce1_local;

assign cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address0 = zext_ln67_1_fu_347_p1;

assign cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_address1 = zext_ln64_3_fu_342_p1;

assign cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0 = cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce0_local;

assign cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1 = cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_ce1_local;

assign grp_fu_392_p0 = grp_fu_392_p00;

assign grp_fu_392_p00 = tmp_fu_242_p3;

assign grp_fu_392_p1 = 9'd13;

assign grp_fu_392_p2 = zext_ln64_2_fu_333_p1;

assign grp_fu_401_p0 = grp_fu_401_p00;

assign grp_fu_401_p00 = tmp_1_fu_254_p3;

assign grp_fu_401_p1 = 9'd13;

assign grp_fu_401_p2 = zext_ln64_2_fu_333_p1;

assign i_fu_234_p3 = ((ap_phi_mux_icmp_ln6228_phi_fu_189_p4[0:0] == 1'b1) ? add_ln61_fu_220_p2 : ap_sig_allocacmp_i26_load);

assign icmp_ln61_fu_284_p2 = ((ap_sig_allocacmp_indvar_flatten25_load == 8'd168) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_278_p2 = ((j_fu_266_p2 == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_352_p2 = ((cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q1 > cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q1) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_366_p2 = ((maxv_2_reg_504 > maxv_1_reg_498) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_376_p2 = ((cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_load_1_reg_510 > maxv_3_fu_370_p3) ? 1'b1 : 1'b0);

assign j_fu_266_p2 = (select_ln61_fu_226_p3 + 4'd1);

assign m_axi_gmem_0_ARADDR = 64'd0;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 32'd0;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_ARVALID = 1'b0;

assign m_axi_gmem_0_AWADDR = gmem_addr_reg_461;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 64'd169;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_RREADY = 1'b0;

assign m_axi_gmem_0_WDATA = maxv_4_reg_516;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 2'd3;

assign m_axi_gmem_0_WUSER = 1'd0;

assign maxv_1_fu_358_p3 = ((icmp_ln66_fu_352_p2[0:0] == 1'b1) ? cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_q1 : cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_1_q1);

assign maxv_3_fu_370_p3 = ((icmp_ln67_fu_366_p2[0:0] == 1'b1) ? maxv_2_reg_504 : maxv_1_reg_498);

assign maxv_4_fu_381_p3 = ((icmp_ln68_fu_376_p2[0:0] == 1'b1) ? cnn_accel_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_8_5_3_0_conv_buf_load_1_reg_510 : maxv_3_fu_370_p3);

assign select_ln61_fu_226_p3 = ((ap_phi_mux_icmp_ln6228_phi_fu_189_p4[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j27_load);

assign sext_ln61_fu_315_p1 = $signed(trunc_ln_fu_305_p4);

assign tmp_1_fu_254_p3 = {{i_fu_234_p3}, {1'd1}};

assign tmp_fu_242_p3 = {{i_fu_234_p3}, {1'd0}};

assign trunc_ln_fu_305_p4 = {{out_r_dout[63:1]}};

assign zext_ln64_2_fu_333_p1 = select_ln61_reg_437_pp0_iter1_reg;

assign zext_ln64_3_fu_342_p1 = grp_fu_392_p3;

assign zext_ln67_1_fu_347_p1 = grp_fu_401_p3;

endmodule //cnn_accel_maxpool
